### PR TITLE
Feature/host python package config

### PR DESCRIPTION
**Pull request by martinbachmanndesignwerk**
Ability to use python-cantools on host
adding host-python-package to aenum, can and wrapt
adding option to enable python3 sqlite and curses for host packages

### CODE REVIEW

**Comment by tpetazzoni** [comment]
Thanks a lot for your contribution! However, the contribution process for Buildroot doesn't take place on Github, but rather by posting patches to the mailing list. The contribution process is described in detail in the Buildroot manual at https://buildroot.org/downloads/manual/manual.html#submitting-patches.

Do you think it would be possible for you to go through this contribution process ? We know it needs a bit more setup than sending pull requests on Github. Thanks a lot!

**Comment by tomoveu** [comment]
@tpetazzoni do you intend to change this?

GitLab, GitHub, anything more developer-friendly

**Comment by tpetazzoni** [comment]
The contribution process is already documented at https://buildroot.org/downloads/manual/manual.html#submitting-patches. Do you find that something is missing?

**Comment by martinbachmanndesignwerk** [comment]
> The contribution process is already documented at https://buildroot.org/downloads/manual/manual.html#submitting-patches. Do you find that something is missing?

It is documented. But im missing a good introduction on how to work with mailing list. That stuff is them fu**ing old that i can not understand in 5minutes how to submit a patch. So my changes will not move to buildroot. Sticking on such old thind make no sense to me.

**Comment by tomoveu** [comment]
@tpetazzoni What I was personally missing is the essential information about `how to contribute` in the project `README`. 

I needed to go through several steps, web links and pages, in order to get to the `manual/manual.html#submitting-patches` page and this was not intuitive from the project's repo. `README` is the first thing we see at GitHub and any other place. Adding something like this after the documentation reference would greatly lower the bad experience for newcomers: 

```
The documentation can be found in docs/manual. .... 

Contributions to buildroot are made by submitting patches to the mailing list. More information can be found at {your link}
```

===

@martinbachmanndesignwerk I understand your frustration, my experience was similar, however Thomas has a good point - `Maintainers' time is very limited` and if the current generation of maintainers are used to working with git send-email, then sticking to git send-email enables more contributions to be reviewed aka more contributors to get their work accepted. 

Alternatively, more maintainers may be another solution, however this takes time to build trust, so we could delegate to more people the responsible task of maintaining. For example, I would be happy to maintain the package I submitted, but I doubt this would happen soon :)

**Pull request closed without merging**
