### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by jacmet** [comment]
Please send patches to the Buildroot mailing list instead: https://buildroot.org/downloads/manual/manual.html#submitting-patches

**Comment by revolter** [comment]
Sent mail with id `20200612094006.77656-1`

**Comment by revolter** [comment]
@jacmet, Did you receive it? As I didn't get any confirmation.

**Comment by jacmet** [comment]
Yes, the patches are now applied and backported to the supported branches

**Pull request closed without merging**
