### PR TITLE
package/mender: update readme.txt

### PR DESCRIPTION
**Pull request by pamolloy**
It looks like the hosted.mender.io UI has changed. The "Organization token" matches the TenantToken created by running `mender setup` and providing the normal user login credentials.

Signed-off-by: Philip Molloy <philip@philipmolloy.com>

### CODE REVIEW

**Comment by pamolloy** [comment]
It looks like `--update` is also deprecated

**Comment by pamolloy** [comment]
Also, note https://lore.kernel.org/buildroot/20220106144301.1022644-1-romain.naour@smile.fr/

**Comment by pamolloy** [comment]
In the above patch series `device_type ` is stored in `/etc/mender`. Following the example in the current `readme.txt` that places it in `/var/lib/mender/` causes a syncing issue because `mender.mk` makes `/var/lib/mender` a symlink to `/var/run/mender` and then rsync fails if you place a file in the overlay at `/var/lib/mender/device_type`.

**Comment by TheYoctoJester** [comment]
@aduskett maybe to review?

**Comment by aduskett** [comment]
This looks good to me!

**Comment by aduskett** [comment]
Yeah, the directory structure needs to be reworked. In all of my projects I symlink /var/lib/mender to /data/mender and use a default service file. We should look into fixing the default paths in buildroot.

**Pull request closed without merging**
